### ISSUE TITLE
amc script error

### ISSUE THREAD

**Issue by wayne54** [filebot/scripts#20]
since upgrading to win 10, latest version of filebot and Java my amc cmd fails as below worked for years before this without any issues any help will be appreciated.
Thanks

SSLException: Received fatal alert: close_notify
javax.net.ssl.SSLException: Received fatal alert: close_notify
	at net.filebot.web.WebRequest.fetch(WebRequest.java:123)
	at net.filebot.web.WebRequest.fetchIfModified(WebRequest.java:101)
	at net.filebot.web.CachedResource.fetchData(CachedResource.java:28)
	at net.filebot.web.CachedResource.fetchData(CachedResource.java:11)
	at net.filebot.web.AbstractCachedResource.fetch(AbstractCachedResource.java:137)
	at net.filebot.web.AbstractCachedResource.get(AbstractCachedResource.java:82)
	at net.filebot.cli.ArgumentProcessor$DefaultScriptProvider.fetchScript(ArgumentProcessor.java:210)
	at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:82)
	at net.filebot.cli.ArgumentProcessor.process(ArgumentProcessor.java:116)
	at net.filebot.Main.main(Main.java:169)
Failure (°_°)

**Comment by rednoah** [comment]
`javax.net.ssl.SSLException: Received fatal alert: close_notify` is very low-level in the Java runtime. Nothing I can do about that. You might be able to find a solution via Google though.
