### ISSUE TITLE
Filebot not working because a script can't be found

### ISSUE THREAD

**Issue by ddddirk** [filebot/scripts#28]
I'm getting this message since approximately last week:

`FileNotFoundException: https://raw.githubusercontent.com/filebot/scripts/v4.1/amc.groovy
java.io.FileNotFoundException: https://raw.githubusercontent.com/filebot/scripts/v4.1/amc.groovy
	at net.filebot.web.WebRequest.fetch(WebRequest.java:140)
	at net.filebot.web.WebRequest.fetchIfModified(WebRequest.java:118)
	at net.filebot.web.CachedResource.fetchData(CachedResource.java:32)
	at net.filebot.web.CachedResource.fetchData(CachedResource.java:11)
	at net.filebot.web.AbstractCachedResource.fetch(AbstractCachedResource.java:133)
	at net.filebot.web.AbstractCachedResource.get(AbstractCachedResource.java:78)
	at net.filebot.cli.ArgumentProcessor$DefaultScriptProvider.fetchScript(ArgumentProcessor.java:198)
	at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:81)
	at net.filebot.cli.ArgumentProcessor.process(ArgumentProcessor.java:108)
	at net.filebot.Main.main(Main.java:192)`

The cause seems to be that the branch v4.1 doesn't exist anymore.

I'm using an r4070 Jar (from sourceforge) on Centos 6 and OpenJDK.

**Comment by rednoah** [comment]
You are not using `r4070`. The logs tell me that you're using `v4.1` which is 2 years old and no longer supported.
