### ISSUE TITLE
error during AMC cleanup step

### ISSUE THREAD

**Issue by garfield69** [filebot/scripts#39]
Just noticed the following error messages in the AMC log:
```
Run script [fn:amc] at [Mon Nov 07 17:27:28 2016]
Parameter: ut_state_allow = 11
Parameter: unsorted = n
Parameter: music = n
Parameter: artwork = n
Parameter: extras = n
Parameter: skipExtract = y
Parameter: clean = y
Parameter: seriesFormat = D:/TV/{n.sortName('$2, $1').replaceTrailingBrackets()}/s{s}e{e.pad(2)} {t.replaceAll(/[!?.]+$/).replaceAll(/[`´‘’?]/, "'").lowerTrail()}
Parameter: movieFormat = X:/AVI/{n.sortName('$2, $1').lowerTrail()} ({y}) {vf} {ac.replace('AC3','DD')}{af.replace('6ch','5.1').replace('2ch','2.0')}
Parameter: ignore = US Open|Formula
Parameter: ut_label = 
Parameter: ut_state = 11
Parameter: ut_title = From [ WWW.TORRENTING.COM ] - Ash.vs.Evil.Dead.S02E06.720p.HEVC.x265-MeGusta
Parameter: ut_kind = multi
Parameter: ut_file = Ash.vs.Evil.Dead.S02E06.720p.HEVC.x265-MeGusta.mkv
Parameter: ut_dir = D:\utorrent\downloads\From [ WWW.TORRENTING.COM ] - Ash.vs.Evil.Dead.S02E06.720p.HEVC.x265-MeGusta
Input: D:\utorrent\downloads\From [ WWW.TORRENTING.COM ] - Ash.vs.Evil.Dead.S02E06.720p.HEVC.x265-MeGusta\Ash.vs.Evil.Dead.S02E06.720p.HEVC.x265-MeGusta.mkv
Group: [tvs:ash vs evil dead] => [Ash.vs.Evil.Dead.S02E06.720p.HEVC.x265-MeGusta.mkv]
Rename episodes using [TheTVDB]
Auto-detected query: [Ash vs Evil Dead]
Fetching episode data for [Ash vs Evil Dead]
Apply Filter: {any{episode; age < 92}{true}}
Include [Ash vs Evil Dead - 2x01 - Home]
Include [Ash vs Evil Dead - 2x02 - The Morgue]
Include [Ash vs Evil Dead - 2x03 - Last Call]
Include [Ash vs Evil Dead - 2x04 - DUI]
Include [Ash vs Evil Dead - 2x05 - Confinement]
Include [Ash vs Evil Dead - 2x06 - Trapped Inside]
Include [Ash vs Evil Dead - 2x07 - Delusion]
Include [Ash vs Evil Dead - 2x08 - Ashy Slashy]
Include [Ash vs Evil Dead - 2x09 - Home Again]
Include [Ash vs Evil Dead - 2x10 - Second Coming]
[MOVE] Rename [D:\utorrent\downloads\From [ WWW.TORRENTING.COM ] - Ash.vs.Evil.Dead.S02E06.720p.HEVC.x265-MeGusta\Ash.vs.Evil.Dead.S02E06.720p.HEVC.x265-MeGusta.mkv] to [D:\TV\Ash vs Evil Dead\s2e06 Trapped Inside.mkv]
Processed 1 files
Clean clutter files and empty folders
No signature of method: java.lang.String.findMatch() is applicable for argument types: (java.util.regex.Pattern) values: [US Open|Formula]
Possible solutions: findMatch(java.lang.String), findAll(java.util.regex.Pattern), findAll(), eachMatch(java.util.regex.Pattern, groovy.lang.Closure), find(java.util.regex.Pattern), eachMatch(java.util.regex.Pattern, groovy.lang.Closure)
groovy.lang.MissingMethodException: No signature of method: java.lang.String.findMatch() is applicable for argument types: (java.util.regex.Pattern) values: [US Open|Formula]
Possible solutions: findMatch(java.lang.String), findAll(java.util.regex.Pattern), findAll(), eachMatch(java.util.regex.Pattern, groovy.lang.Closure), find(java.util.regex.Pattern), eachMatch(java.util.regex.Pattern, groovy.lang.Closure)
	at Script8$_run_closure13.doCall(Script8.groovy:20)
	at Script8$_run_closure16.doCall(Script8.groovy:57)
	at net.filebot.cli.ScriptShellMethods.getFiles(ScriptShellMethods.java:140)
	at Script8.run(Script8.groovy:57)
	at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:62)
	at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:72)
	at net.filebot.cli.ScriptShellBaseClass.executeScript(ScriptShellBaseClass.java:115)
	at net.filebot.cli.ScriptShellBaseClass.executeScript(ScriptShellBaseClass.java:98)
	at Script1.run(Script1.groovy:676)
	at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:62)
	at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:72)
	at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:113)
	at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:28)
	at net.filebot.Main.main(Main.java:124)
Failure (°_°)
```
I call AMC via uTorrent, preferences, Run Program with the following command:
```
"C:\Program Files\FileBot\filebot.launcher.exe" -script  fn:amc --action move -non-strict -no-xattr --log-file "d:/tv/amc.log" --filter "any{episode; age < 92}{true}" --def "@d:/TV/amc_args.txt" "ut_label=%L" "ut_state=%S" "ut_title=%N" "ut_kind=%K" "ut_file=%F" "ut_dir=%D"
```
and use the following AMC arguments file:
```
ut_state_allow=11
unsorted=n
music=n
artwork=n
extras=n
skipExtract=y
clean=y
seriesFormat=D:/TV/{n.sortName('$2, $1').replaceTrailingBrackets()}/s{s}e{e.pad(2)} {t.replaceAll(/[!?.]+$/).replaceAll(/[`´‘’?]/, "'").lowerTrail()}
movieFormat=X:/AVI/{n.sortName('$2, $1').lowerTrail()} ({y}) {vf} {ac.replace('AC3','DD')}{af.replace('6ch','5.1').replace('2ch','2.0')}
ignore=US Open|Formula
```
I'm using win7 x32 FileBot 4.7.2

**Comment by garfield69** [comment]
Ah. Never mind. found https://www.filebot.net/forums/viewtopic.php?f=6&t=4268&p=24213#p24210 and switching to use dev:amc circumvents the problem. I'll switch back to fn:amc in a day or two.

**Comment by rednoah** [comment]
Should be fixed with `Script Bundle: 2016-11-07 (r458)`. May need to call `-clear-cache` to make sure `fn:amc` calls the latest published revision.
