### ISSUE TITLE
FileBot URL Timeout

### ISSUE THREAD

**Issue by Tanen** [filebot/scripts#41]
Hello,

My FileBot is no longer working since two or three days, when I'm trying to scrap a movie, I got this error from console :

```
filebot
Fetch failed: java.net.SocketTimeoutException: connect timed out [https://app.filebot.net/update.xml]
Failed to check for updates
java.net.SocketTimeoutException: connect timed out
        at net.filebot.web.WebRequest.fetch(WebRequest.java:143)
        at net.filebot.CachedResource.lambda$fetchIfModified$9(CachedResource.java:216)
        at net.filebot.CachedResource.lambda$null$0(CachedResource.java:87)
        at net.filebot.CachedResource.retry(CachedResource.java:120)
        at net.filebot.CachedResource.lambda$get$1(CachedResource.java:87)
        at net.filebot.Cache.computeIf(Cache.java:90)
        at net.filebot.CachedResource.get(CachedResource.java:82)
        at net.filebot.Main.checkUpdate(Main.java:262)
        at net.filebot.Main.onStart(Main.java:178)
        at net.filebot.Main.lambda$null$0(Main.java:136)
        at net.filebot.util.ui.SwingUI$SwingRunnable.doInBackground(SwingUI.java:426)
        at net.filebot.util.ui.SwingUI$SwingRunnable.doInBackground(SwingUI.java:416)
Caused by: java.net.SocketTimeoutException: connect timed out
        at net.filebot.web.WebRequest.fetch(WebRequest.java:140)
        ... 11 more

Fetch failed: java.net.SocketTimeoutException: connect timed out [https://app.filebot.net/data/exclude-blacklist.txt.xz]
Failed to load clutter file filter: connect timed out
java.net.SocketTimeoutException: connect timed out
        at net.filebot.web.WebRequest.fetch(WebRequest.java:143)
        at net.filebot.CachedResource.lambda$fetchIfModified$9(CachedResource.java:216)
        at net.filebot.CachedResource.lambda$null$0(CachedResource.java:87)
        at net.filebot.CachedResource.retry(CachedResource.java:120)
        at net.filebot.CachedResource.retry(CachedResource.java:132)
        at net.filebot.CachedResource.retry(CachedResource.java:132)
        at net.filebot.CachedResource.lambda$get$1(CachedResource.java:87)
        at net.filebot.Cache.computeIf(Cache.java:90)
        at net.filebot.CachedResource.get(CachedResource.java:82)
        at net.filebot.media.ReleaseInfo.lambda$resource$18(ReleaseInfo.java:489)
        at net.filebot.MemoizedResource.get(Resource.java:36)
        at net.filebot.media.ReleaseInfo.getExcludePattern(ReleaseInfo.java:354)
        at net.filebot.media.ReleaseInfo.getClutterFileFilter(ReleaseInfo.java:407)
        at net.filebot.media.MediaDetection.getClutterFileFilter(MediaDetection.java:85)
        at net.filebot.ui.rename.MovieMatcher.match(MovieMatcher.java:74)
        at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:883)
        at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:879)
Caused by: java.net.SocketTimeoutException: connect timed out
        at net.filebot.web.WebRequest.fetch(WebRequest.java:140)
        ... 16 more

Fetch failed: java.net.SocketTimeoutException: connect timed out [https://app.filebot.net/data/query-blacklist.txt.xz]
SocketTimeoutException: connect timed out
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: connect timed out
        at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.done(RenamePanel.java:898)
Caused by: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: connect timed out
        at net.filebot.ui.rename.MovieMatcher.match(MovieMatcher.java:178)
        at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:883)
        at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:879)
Caused by: java.net.SocketTimeoutException: connect timed out
        at net.filebot.web.WebRequest.fetch(WebRequest.java:143)
        at net.filebot.CachedResource.lambda$fetchIfModified$9(CachedResource.java:216)
        at net.filebot.CachedResource.lambda$null$0(CachedResource.java:87)
        at net.filebot.CachedResource.retry(CachedResource.java:120)
        at net.filebot.CachedResource.retry(CachedResource.java:132)
        at net.filebot.CachedResource.retry(CachedResource.java:132)
        at net.filebot.CachedResource.lambda$get$1(CachedResource.java:87)
        at net.filebot.Cache.computeIf(Cache.java:90)
        at net.filebot.CachedResource.get(CachedResource.java:82)
        at net.filebot.media.ReleaseInfo.lambda$resource$18(ReleaseInfo.java:489)
        at net.filebot.MemoizedResource.get(Resource.java:36)
        at net.filebot.media.ReleaseInfo.getStructureRootPattern(ReleaseInfo.java:263)
        at net.filebot.media.MediaDetection.isStructureRoot(MediaDetection.java:1015)
        at net.filebot.media.MediaDetection.guessMovieFolder(MediaDetection.java:808)
        at net.filebot.media.MediaDetection.detectMovie(MediaDetection.java:605)
        at net.filebot.ui.rename.MovieMatcher.lambda$null$2(MovieMatcher.java:172)
Caused by: java.net.SocketTimeoutException: connect timed out
        at net.filebot.web.WebRequest.fetch(WebRequest.java:140)
        ... 15 more
```

When I try to access your website or this URL my browser is very slow and 1 time on 5 try I can display webpage. I've try from 5 differents Internet providers, same result ...

This is traceroute for this URLs : 
```
[root@pfsense.me]/root: traceroute www.filebot.net
traceroute: Warning: www.filebot.net has multiple addresses; using 104.27.153.61
traceroute to www.filebot.net (104.27.153.61), 64 hops max, 40 byte packets
 1  XXXXXXXXXXXXXXXXXXXXXXXXX 41.167 ms  36.099 ms  40.670 ms
 2  XXXXXXXXXXXXXXXXXXXXXXXXX 30.649 ms  130.684 ms  31.551 ms
 3  XXXXXXXXXXXXXXXXXXXXXXXXX 46.891 ms  38.933 ms  43.813 ms
 4  XXXXXXXXXXXXXXXXXXXXXXXXX 51.902 ms  53.283 ms  44.245 ms
 5  XXXXXXXXXXXXXXXXXXXXXXXXX 53.388 ms  41.892 ms  43.053 ms
 6  be4204.ccr21.par04.atlas.cogentco.com (149.11.115.13)  95.027 ms  100.518 ms  100.521 ms
 7  be12309.ccr42.par01.atlas.cogentco.com (154.54.39.65)  100.748 ms  93.116 ms
    be12308.ccr41.par01.atlas.cogentco.com (130.117.49.41)  101.118 ms
 8  be12489.ccr42.lon13.atlas.cogentco.com (154.54.57.69)  108.722 ms  101.252 ms
    be12497.ccr41.lon13.atlas.cogentco.com (154.54.56.129)  91.358 ms
 9  be2871.ccr21.lon01.atlas.cogentco.com (154.54.58.186)  106.524 ms
    be2868.ccr21.lon01.atlas.cogentco.com (154.54.57.154)  100.117 ms  107.390 ms
10  149.14.80.206 (149.14.80.206)  101.610 ms  110.591 ms  111.960 ms
11  104.27.153.61 (104.27.153.61)  108.226 ms  104.516 ms  101.816 ms

[root@pfsense.me]/root: traceroute app.filebot.net
traceroute: Warning: app.filebot.net has multiple addresses; using 104.27.152.61
traceroute to app.filebot.net (104.27.152.61), 64 hops max, 40 byte packets
 1  XXXXXXXXXXXXXXXXXXXXXXXXX 29.068 ms  40.486 ms  42.771 ms
 2  XXXXXXXXXXXXXXXXXXXXXXXXX 29.407 ms  46.696 ms  35.424 ms
 3  XXXXXXXXXXXXXXXXXXXXXXXXX 42.598 ms  41.845 ms  43.814 ms
 4  XXXXXXXXXXXXXXXXXXXXXXXXX 51.759 ms  49.809 ms  64.142 ms
 5  XXXXXXXXXXXXXXXXXXXXXXXXX 49.037 ms  47.638 ms  62.914 ms
 6  be4204.ccr21.par04.atlas.cogentco.com (149.11.115.13)  97.882 ms  92.609 ms  100.052 ms
 7  be12309.ccr42.par01.atlas.cogentco.com (154.54.39.65)  99.980 ms
    be12308.ccr41.par01.atlas.cogentco.com (130.117.49.41)  109.514 ms
    be12309.ccr42.par01.atlas.cogentco.com (154.54.39.65)  95.871 ms
 8  be12497.ccr41.lon13.atlas.cogentco.com (154.54.56.129)  104.826 ms
    be12489.ccr42.lon13.atlas.cogentco.com (154.54.57.69)  107.157 ms  96.441 ms
 9  be2868.ccr21.lon01.atlas.cogentco.com (154.54.57.154)  101.096 ms
    be2871.ccr21.lon01.atlas.cogentco.com (154.54.58.186)  101.448 ms
    be2868.ccr21.lon01.atlas.cogentco.com (154.54.57.154)  109.141 ms
10  149.14.80.206 (149.14.80.206)  103.919 ms  96.160 ms  100.058 ms
11  104.27.152.61 (104.27.152.61)  104.856 ms  107.062 ms  98.230 ms
[root@pfsense.me]/root:
```

Can you please let me know if you have something wrong with your website or your provider or if it's just a local problem or my installation/connexion ?

Thanks in advance.

**Comment by rednoah** [comment]
CloudFlare should be serving all the static resources, so it should be very fast.

What does `curl -I https://app.filebot.net/update.xml` say?

**Comment by Tanen** [comment]
Hi Mister rednoah,

thank you for your reply !

See below the result :

```
[root@pfsense.me]/root: curl -I https://app.filebot.net/update.xml
HTTP/1.1 200 OK
Date: Fri, 23 Dec 2016 19:40:52 GMT
Content-Type: text/xml
Content-Length: 703
Connection: keep-alive
Set-Cookie: __cfduid=d562f76ff5439e5614734d4db31c0b4131482522052; expires=Sat, 23-Dec-17 19:40:52 GMT; path=/; domain=.filebot.net; HttpOnly
Vary: Host
Last-Modified: Sat, 26 Nov 2016 05:18:51 GMT
ETag: "2bf-5422d5fcc61e2"
Cache-Control: public, max-age=2678400
Expires: Mon, 23 Jan 2017 19:40:52 GMT
CF-Cache-Status: HIT
Accept-Ranges: bytes
Server: cloudflare-nginx
CF-RAY: 315e49ab097735b4-LHR
```

I stay connected if needed !

Thnaks again.

**Comment by rednoah** [comment]
Well looks fine.

How about this?
`curl -v https://app.filebot.net/update.xml`

**Comment by Tanen** [comment]
Result for curl commande :

```
[root@pfsense.me]/root: curl -v https://app.filebot.net/update.xml
*   Trying 104.27.153.61...
* Connected to app.filebot.net (104.27.153.61) port 443 (#0)
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/share/certs/ca-root-nss.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Unknown (67):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni142884.cloudflaressl.com
*  start date: Dec 20 00:00:00 2016 GMT
*  expire date: Jun 25 23:59:59 2017 GMT
*  subjectAltName: host "app.filebot.net" matched cert's "*.filebot.net"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
> GET /update.xml HTTP/1.1
> Host: app.filebot.net
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 23 Dec 2016 20:36:31 GMT
< Content-Type: text/xml
< Content-Length: 703
< Connection: keep-alive
< Set-Cookie: __cfduid=d09ba7673bb40bf29e052b33d44421bc61482525391; expires=Sat, 23-Dec-17 20:36:31 GMT; path=/; domain=.filebot.net; HttpOnly
< Vary: Host
< Last-Modified: Sat, 26 Nov 2016 05:18:51 GMT
< ETag: "2bf-5422d5fcc61e2"
< Cache-Control: public, max-age=2678400
< Expires: Mon, 23 Jan 2017 20:36:31 GMT
< CF-Cache-Status: HIT
< Accept-Ranges: bytes
< Server: cloudflare-nginx
< CF-RAY: 315e9b30a89c3548-LHR
<
<?xml version="1.0" encoding="UTF-8"?>
<update>
        <name>FileBot 4.7.5</name>
        <revision>4600</revision>
        <title>New updates available</title>
        <message><![CDATA[<html>
                <b>FileBot 4.7.5</b><br>
                This release features:<br>
                + Keyboard shortcuts for calling user-defined Presets (Numpad 1..9)<br>
                + Improved episode auto-detection<br>
                + Improved file sort order<br>
                + Improved bindings: {plex}, {t}, {votes}, {group} and {tags}<br>
                + Reduce xattr metadata size<br>
                + Lots of bugfixes<br>
        <html>]]></message>
        <discussion><![CDATA[http://www.filebot.net/forums/viewtopic.php?f=7&t=3709&p=24567#p24567]]></discussion>
        <download><![CDATA[http://www.filebot.net/#download]]></download>
* Connection #0 to host app.filebot.net left intact

```

```
C:\FileBot\filebot.exe
Fetch failed: java.net.SocketTimeoutException: connect timed out [https://app.filebot.net/data/exclude-blacklist.txt.xz]
Failed to load clutter file filter: connect timed out
java.net.SocketTimeoutException: connect timed out
        at net.filebot.web.WebRequest.fetch(WebRequest.java:143)
        at net.filebot.CachedResource.lambda$fetchIfModified$9(CachedResource.java:216)
        at net.filebot.CachedResource.lambda$null$0(CachedResource.java:87)
        at net.filebot.CachedResource.retry(CachedResource.java:120)
        at net.filebot.CachedResource.retry(CachedResource.java:132)
        at net.filebot.CachedResource.retry(CachedResource.java:132)
        at net.filebot.CachedResource.lambda$get$1(CachedResource.java:87)
        at net.filebot.Cache.computeIf(Cache.java:90)
        at net.filebot.CachedResource.get(CachedResource.java:82)
        at net.filebot.media.ReleaseInfo.lambda$resource$18(ReleaseInfo.java:489)
        at net.filebot.MemoizedResource.get(Resource.java:36)
        at net.filebot.media.ReleaseInfo.getExcludePattern(ReleaseInfo.java:354)
        at net.filebot.media.ReleaseInfo.getClutterFileFilter(ReleaseInfo.java:407)
        at net.filebot.media.MediaDetection.getClutterFileFilter(MediaDetection.java:85)
        at net.filebot.ui.rename.MovieMatcher.match(MovieMatcher.java:74)
        at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:883)
        at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:879)
Caused by: java.net.SocketTimeoutException: connect timed out
        at net.filebot.web.WebRequest.fetch(WebRequest.java:140)
        ... 16 more

Fetch failed: java.net.SocketTimeoutException: connect timed out [https://app.filebot.net/data/query-blacklist.txt.xz]
SocketTimeoutException: connect timed out
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: connect timed out
        at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.done(RenamePanel.java:898)
Caused by: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: connect timed out
        at net.filebot.ui.rename.MovieMatcher.match(MovieMatcher.java:178)
        at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:883)
        at net.filebot.ui.rename.RenamePanel$AutoCompleteAction$1.doInBackground(RenamePanel.java:879)
Caused by: java.net.SocketTimeoutException: connect timed out
        at net.filebot.web.WebRequest.fetch(WebRequest.java:143)
        at net.filebot.CachedResource.lambda$fetchIfModified$9(CachedResource.java:216)
        at net.filebot.CachedResource.lambda$null$0(CachedResource.java:87)
        at net.filebot.CachedResource.retry(CachedResource.java:120)
        at net.filebot.CachedResource.retry(CachedResource.java:132)
        at net.filebot.CachedResource.retry(CachedResource.java:132)
        at net.filebot.CachedResource.lambda$get$1(CachedResource.java:87)
        at net.filebot.Cache.computeIf(Cache.java:90)
        at net.filebot.CachedResource.get(CachedResource.java:82)
        at net.filebot.media.ReleaseInfo.lambda$resource$18(ReleaseInfo.java:489)
        at net.filebot.MemoizedResource.get(Resource.java:36)
        at net.filebot.media.ReleaseInfo.getStructureRootPattern(ReleaseInfo.java:263)
        at net.filebot.media.MediaDetection.isStructureRoot(MediaDetection.java:1015)
        at net.filebot.media.MediaDetection.guessMovieFolder(MediaDetection.java:808)
        at net.filebot.media.MediaDetection.detectMovie(MediaDetection.java:605)
        at net.filebot.ui.rename.MovieMatcher.lambda$null$2(MovieMatcher.java:172)
Caused by: java.net.SocketTimeoutException: connect timed out
        at net.filebot.web.WebRequest.fetch(WebRequest.java:140)
        ... 15 more

```
I suspect a loadbalancing problem ... I have 4 WANs and this is probably the clue ... I'll come back in few minutes to let you know !

Thanks again.

**Comment by Tanen** [comment]
Ok, all my apologize ...

It was the clue ! My loadbalancing system is getting a too much long reply time, so a second try is sent from another WAN (with another IP) and your server is rejecting second IP as the first connexion was from another WAN ...

Reply time is very long from my windows computers, not the same from my Unix machine, I don't understand why ATM ...

Thanks again for your help !

One last question, I've bought FileBot licence from Windows Store, but, it's a different program or I have exactly the same function as the one from website ? (I'm needing portable edition, so I want to know if Windows Store version is different from other).

If function are different, as I am already a donator (I've ssent you money from donate PayPal button, can I expect a full functionality as protable version ?

Thanks in advance.

**Comment by rednoah** [comment]
Windows Store and portable version are more or less the same. You probably won't notice a difference.

The portable is more platform independent while the Windows Store version enables various features and optimizations that require Windows 10 and higher.
