### ISSUE TITLE
script fn:suball fails immediately if movies have trailers

### ISSUE THREAD

**Issue by tmack8001** [filebot/scripts#42]
```
java.nio.file.NoSuchFileException: /mnt/drobo-nas/Movies/Indiana Jones and the Last Crusade (1989)/trailers/Indiana Jones And The Last Crusade - Official�� Trailer [HD].mp4
java.lang.RuntimeException: java.nio.file.NoSuchFileException: /mnt/drobo-nas/Movies/Indiana Jones and the Last Crusade (1989)/trailers/Indiana Jones And The Last Crusade - Official�� Trailer [HD].mp4
	at net.filebot.format.ExpressionFormatMethods.getCreationDate(ExpressionFormatMethods.java:418)
	at Script1$_run_closure17.doCall(Script1.groovy:27)
	at Script1$_run_closure18.doCall(Script1.groovy:72)
	at net.filebot.cli.ScriptShellMethods.getFiles(ScriptShellMethods.java:140)
	at Script1.run(Script1.groovy:72)
	at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:62)
	at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:72)
	at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:113)
	at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:28)
	at net.filebot.Main.main(Main.java:124)
Caused by: java.nio.file.NoSuchFileException: /mnt/drobo-nas/Movies/Indiana Jones and the Last Crusade (1989)/trailers/Indiana Jones And The Last Crusade - Official�� Trailer [HD].mp4
	at net.filebot.format.ExpressionFormatMethods.getCreationDate(ExpressionFormatMethods.java:411)
	... 9 more
Failure (°_°)
```

**Comment by tmack8001** [comment]
Actually looking at the file name it seems to be related to the characters used in the title of the video file (which was downloaded along side the video).

```
Indiana Jones And The Last Crusade - Official® Trailer [HD].mp4
```

**Comment by rednoah** [comment]
`filebot -script fn:sysinfo` output?

**Comment by tmack8001** [comment]
```
$ filebot -script fn:sysinfo
FileBot 4.7.2 (r4178)
JNA Native: 4.0.1
MediaInfo: 0.7.70
Apache Commons VFS: [zip, rar]
Chromaprint: java.io.IOException: Cannot run program "fpcalc": error=2, No such file or directory
Extended Attributes: OK
Script Bundle: 2016-11-07 (r458)
Groovy: 2.4.7
JRE: Java(TM) SE Runtime Environment 1.8.0_65 (headless)
JVM: 32-bit Java HotSpot(TM) Client VM
CPU/MEM: 4 Core / 224 MB Max Memory / 10 MB Used Memory
OS: Linux (arm)
Package: IPKG
Data: /usr/share/filebot/data/pi
uname: Linux piserver 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l GNU/Linux
```

```
$ filebot -script fn:sysenv
# Environment Variables #
_: /usr/local/bin/filebot
INFINALITY_FT_BRIGHTNESS: 0
MAIL: /var/mail/pi
INFINALITY_FT_FILTER_PARAMS: 11 22 38 22 11
LD_LIBRARY_PATH: /usr/share/filebot
INFINALITY_FT_FRINGE_FILTER_STRENGTH: 0
XDG_RUNTIME_DIR: /run/user/1000
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
INFINALITY_FT_USE_KNOWN_SETTINGS_ON_SELECTED_FONTS: true
SSH_CLIENT: 192.168.86.100 52832 22
XFILESEARCHPATH: /usr/dt/app-defaults/%L/Dt
INFINALITY_FT_USE_VARIOUS_TWEAKS: true
INFINALITY_FT_STEM_SNAPPING_SLIDING_SCALE: 40
INFINALITY_FT_BOLD_EMBOLDEN_Y_VALUE: 0
INFINALITY_FT_STEM_ALIGNMENT_STRENGTH: 25
INFINALITY_FT_STEM_FITTING_STRENGTH: 25
INFINALITY_FT_WINDOWS_STYLE_SHARPENING_STRENGTH: 10
TERM: xterm-256color
NLSPATH: /usr/dt/lib/nls/msg/%L/%N.cat
INFINALITY_FT_AUTOHINT_VERTICAL_STEM_DARKEN_STRENGTH: 25
LANG: en_US.UTF-8
LS_COLORS: rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
INFINALITY_FT_AUTOHINT_INCREASE_GLYPH_HEIGHTS: true
INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH: 0
INFINALITY_FT_GAMMA_CORRECTION: 0 100
LOGNAME: pi
INFINALITY_FT_GLOBAL_EMBOLDEN_Y_VALUE: 0
SHLVL: 1
INFINALITY_FT_GRAYSCALE_FILTER_STRENGTH: 0
LC_ALL: en_US.UTF-8
INFINALITY_FT_AUTOHINT_SNAP_STEM_HEIGHT: 100
INFINALITY_FT_BOLD_EMBOLDEN_X_VALUE: 0
HOME: /home/pi
SSH_CONNECTION: 192.168.86.100 52832 192.168.86.104 22
SSH_TTY: /dev/pts/1
XDG_SESSION_ID: c34
SHELL: /bin/bash
INFINALITY_FT_GLOBAL_EMBOLDEN_X_VALUE: 0
INFINALITY_FT_CONTRAST: 0
PWD: /home/pi
INFINALITY_FT_AUTOHINT_HORIZONTAL_STEM_DARKEN_STRENGTH: 10
USER: pi


# Java System Properties #
path.separator: :
java.vm.name: Java HotSpot(TM) Client VM
java.io.tmpdir: /usr/share/filebot/data/pi/temp
user.country: US
user.home: /usr/share/filebot/data/pi
useExtendedFileAttributes: true
net.filebot.Archive.extractor: ApacheVFS
org.apache.commons.logging.Log: org.apache.commons.logging.impl.NoOpLog
java.vm.vendor: Oracle Corporation
user.language: en
java.vendor: Oracle Corporation
java.vendor.url.bug: http://bugreport.sun.com/bugreport/
swing.crossplatformlaf: javax.swing.plaf.nimbus.NimbusLookAndFeel
sun.net.client.defaultReadTimeout: 60000
java.specification.name: Java Platform API Specification
os.name: Linux
java.runtime.name: Java(TM) SE Runtime Environment
application.deployment: ipkg
file.separator: /
sun.net.client.defaultConnectTimeout: 10000
java.vm.specification.version: 1.8
sun.boot.class.path: /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/resources.jar:/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/rt.jar:/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/sunrsasign.jar:/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/jsse.jar:/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/jce.jar:/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/charsets.jar:/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/jfr.jar:/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/classes
java.version: 1.8.0_65
http.agent: FileBot 4.7.2
java.library.path: /usr/share/filebot:/usr/java/packages/lib/arm:/lib:/usr/lib
unixfs: false
awt.toolkit: sun.awt.X11.XToolkit
java.vm.specification.name: Java Virtual Machine Specification
os.version: 4.4.34-v7+
useCreationDate: false
file.encoding: UTF-8
java.awt.printerjob: sun.print.PSPrinterJob
grape.root: /usr/share/filebot/data/pi/grape
java.class.version: 52.0
java.ext.dirs: /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/ext:/usr/java/packages/lib/ext
java.specification.version: 1.8
net.filebot.AcoustID.fpcalc: fpcalc
java.vendor.url: http://java.oracle.com/
sun.os.patch.level: unknown
sun.java.launcher: SUN_STANDARD
os.arch: arm
user.dir: /home/pi
line.separator:

user.timezone:
sun.cpu.endian: little
java.vm.specification.vendor: Oracle Corporation
java.home: /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre
sun.management.compiler: HotSpot Client Compiler
sun.arch.data.model: 32
java.endorsed.dirs: /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/endorsed
file.encoding.pkg: sun.io
java.specification.vendor: Oracle Corporation
sun.boot.library.path: /usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre/lib/arm
sun.jnu.encoding: UTF-8
sun.arch.abi: gnueabihf
java.runtime.version: 1.8.0_65-b17
java.vm.info: mixed mode
java.vm.version: 25.65-b01
sun.io.unicode.encoding: UnicodeLittle
java.awt.graphicsenv: sun.awt.X11GraphicsEnvironment
application.dir: /usr/share/filebot/data/pi
java.class.path: /usr/share/filebot/FileBot.jar
sun.java.command: /usr/share/filebot/FileBot.jar -script fn:sysenv
sun.cpu.isalist:
user.name: pi


# Arguments #
No such property: argumentArray for class: net.filebot.cli.ArgumentBean
groovy.lang.MissingPropertyException: No such property: argumentArray for class: net.filebot.cli.ArgumentBean
	at Script1.run(Script1.groovy:17)
	at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:62)
	at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:72)
	at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:113)
	at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:28)
	at net.filebot.Main.main(Main.java:124)
Failure (°_°)
```

**Comment by tmack8001** [comment]
FYI changing that filename to remove the "®" character allowed the script to continue (until the next file with special characters)

**Comment by rednoah** [comment]
1.
`FileBot 4.7.2` is **not** the latest version.

2.
Did you read *Q: I'm running FileBot on a Linux machine and non-ASCII characters get all messed up. Why do unicode characters not work?* in the [FAQ](https://www.filebot.net/forums/viewtopic.php?f=3&t=7) yet?

**Comment by tmack8001** [comment]
@rednoah yeah that fixed my issues, thanks for the pointers. I looked through FAQ and somehow didn't find it, probably as I was searching for subtitle specific issues.

**Comment by rednoah** [comment]
Does this work as well?
```
export LANG="C.UTF-8"
export LC_ALL="C.UTF-8"
```

**Comment by tmack8001** [comment]
When testing those locales I got the following errors:

```
{textLanguages} => Expression yields empty value: Binding "textLanguages": Could not initialize class net.filebot.mediainfo.MediaInfoLibrary
{duration} => Expression yields empty value: Binding "duration": Could not initialize class net.filebot.mediainfo.MediaInfoLibrary
```

**Comment by rednoah** [comment]
`libmediainfo` is broken. Run `filebot -script fn:sysinfo` and see if it still says `MediaInfo: 0.7.70`.

You're probably missing the native libraries:
https://github.com/filebot/filebot/tree/master/lib/native/linux-armv7l

**Comment by tmack8001** [comment]
Realized what changed. I updated to 4.7.7 and used the suggested noarch packaging for use with my Raspberry Pi 3. Now JNA Native, MediaInfo and Chromaprint aren't being found. Need to resolve all these references first.

**Comment by rednoah** [comment]
Does the Pi OS have `ipkg`? I usually recommend the portable package.

**Comment by tmack8001** [comment]
Oh sorry meant "portable" packing not noarch.

**Comment by tmack8001** [comment]
According to my package manager

```
mediainfo is already the newest version.
libjna-java is already the newest version.
```

Looking at my /usr/bin folder I see the following that might be causing some trouble

```
$ ls -ltr /usr/lib/arm-linux-gnueabihf | grep libmediainfo
lrwxrwxrwx 1 root root       21 Sep 24  2014 libmediainfo.so.0 -> libmediainfo.so.0.0.0
-rw-r--r-- 1 root root  5594280 Sep 24  2014 libmediainfo.so.0.0.0
```

```
$ ls -ltr /usr/lib/arm-linux-gnueabihf | grep libzen
lrwxrwxrwx 1 root root       15 Jun  6  2013 libzen.so.0 -> libzen.so.0.0.0
-rw-r--r-- 1 root root   257224 Jun  6  2013 libzen.so.0.0.0
```

So I went in a symlinked the so.0 to what I think the expected path would be ex "libzen.so", but unfortunately that didn't resolve the issues either.

**Comment by tmack8001** [comment]
I have resolved the Chromaprint fpcalc by downloading the fpcalc file from this repo and symlinking to /usr/local/bin, but stil having the JNA Native and MediaInfo issues.

```
$ filebot -script fn:sysinfo
FileBot 4.7.7 (r4678)
JNA Native: java.lang.UnsatisfiedLinkError: Can't obtain static method fromNative(Method, Object) from class com.sun.jna.Native
MediaInfo: net.filebot.mediainfo.MediaInfoException: Unable to load arm (32-bit) native library libmediainfo.so: Could not initialize class com.sun.jna.Native
Apache Commons VFS: [zip, rar]
Chromaprint: 1.4.2
Extended Attributes: OK
Script Bundle: 2017-01-05 (r470)
Groovy: 2.4.7
JRE: Java(TM) SE Runtime Environment 1.8.0_65
JVM: 32-bit Java HotSpot(TM) Client VM
CPU/MEM: 4 Core / 224 MB Max Memory / 8 MB Used Memory
OS: Linux (arm)
Package: PORTABLE
Data: /usr/share/filebot/bin/data
uname: Linux piserver 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l GNU/Linux
Done ヾ(＠⌒ー⌒＠)ノ
```

**Comment by rednoah** [comment]
The latest portable beta release includes all the native libraries and should work out of the box:
https://sourceforge.net/projects/filebot/files/filebot/HEAD/FileBot_4.7.8_B2/FileBot_4.7.8-portable.tar.xz

**Comment by tmack8001** [comment]
that works, thanks for the help and the link to the 4.7.8 beta release. keep up the great support
