### ISSUE TITLE
Using amc with filebot 4.8.5 throws error

### ISSUE THREAD

**Issue by HLeithner** [filebot/scripts#53]
I tried to modify amc.groovy and tested the downloaded amc.groovy with my current script script by only changing -script fn:amc to -script /path/to/amc.groovy (downloaded with wget).

Version used: https://github.com/filebot/scripts/commit/31f3390030c0d9d5a02fe360b61f8b2f61a62c7b

The Error message:
```
CmdlineException: Failed to match files to episode data
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/usr/share/filebot/jar/groovy.jar) to method javax.script.AbstractScriptEngine.getScriptContext(javax.script.Bindings)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.sendmail() is applicable for argument types: (LinkedHashMap) values: [[subject:[FileBot] Failure, message:Failed to process group: [tvs:zzz], ...]]
Possible solutions: findAll()
groovy.lang.MissingMethodException: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.sendmail() is applicable for argument types: (LinkedHashMap) values: [[subject:[FileBot] Failure, message:Failed to process group: [tvs:zzz], ...]]
Possible solutions: findAll()
        at Script1.sendEmailReport(Script1.groovy:104)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at Script1.fail(Script1.groovy:111)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at Script1$_run_closure54.doCall(Script1.groovy:448)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at Script1.run(Script1.groovy:418)
        at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:64)
        at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:74)
        at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:149)
        at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:36)
        at net.filebot.Main.main(Main.java:128)
```

I only what to create a PR for the "Failed" E-Mail Report to add the path used because "Finished without processing any files" is a bit useless ;-)

**Comment by rednoah** [comment]
So the revision from `Oct 21, 2018` doesn't work? Are a modified version made by you? Have you tried the latest official one?

The email code hasn't been touched in years, but if you just `wget` the script, then you're gonna be missing the `lib/ant` dependency that defines the `sendmail` function.

I recommend using `git` instead of `wget` if you want to have a local script repository:
https://github.com/filebot/scripts#clone

**Comment by HLeithner** [comment]
correct this was my fault not cloning the repo.
