### ISSUE TITLE
Feature Request: Generate Episode NFO Files

### ISSUE THREAD

**Issue by HarryMuscle** [filebot/scripts#67]
Some of us like to curate all information including episode details.  Unfortunately creating episode nfo files doesn't seem to be possible in the AMC script.  That means either using FileBot first and then having to use another tool to generate the episode nfo files or just using another tool that does support doing everything including generating episode nfo files.  Using two tools will probably cause people to switch away from FileBot in favor of the one tool that does everything.

**Comment by rednoah** [comment]
Episode NFO files are rarely used, and so the NFO file format / XML elements are much less well-defined. What software do you want to generate NFO files for? What pieces of information do you need?

Presumably, you'll want to create NFO files for Kodi:
https://kodi.wiki/view/NFO_files/Episodes

Adding episode nfo support to existing scripts is not desirable. Not everyone uses Kodi. Fewer still want episode nfo files. That said, a standalone script that reads xattr episode info and then generates nfo files is perfectly conceivable. Different databases will allow for different episode-specific information. FileBot does however have an abstraction layer, so writing some basic episode info to a text file is easy because FileBot APIs already handle most of the work.

e.g.
```
filebot -script episode-nfo.groovy /path/to/input
```
```
args.files.each{ f ->
	def m = f.metadata
	if (m instanceof Episode) {
		log.finest "[FILE] $f [$m]"
		m.info.properties.each{ n, v ->
			log.info "[INFO] $n: $v"
		}
	}
}
```

**Comment by rednoah** [comment]
I've added a script with basic functionality, to be extended or modified as needed:
https://github.com/filebot/scripts/commit/6cfc231560f9e03e986c155f5ec8986ec9dbe405

**Comment by HarryMuscle** [comment]
Awesome, thanks for creating that script.  I just tried running it on the original Star Trek series and unfortunately I got the following error:

```
Generate Episode NFO: Star Trek - 1x01 - The Man Trap [/TV Shows/Star Trek (1966)/Season 01/Star Trek (1966) - S01E01 - The Man Trap.nfo]
No such property: image for class: net.filebot.web.EpisodeInfo
groovy.lang.MissingPropertyException: No such property: image for class: net.filebot.web.EpisodeInfo
        at Script1$_fetchEpisodeNfo_closure2$_closure3.doCall(Script1.groovy:26)
        at Script1$_fetchEpisodeNfo_closure2$_closure3.doCall(Script1.groovy)
        at Script1$_fetchEpisodeNfo_closure2.doCall(Script1.groovy:10)
        at Script1$_fetchEpisodeNfo_closure2.doCall(Script1.groovy)
        at net.filebot.cli.ScriptShellBaseClass.XML(Unknown Source)
        at Script1.fetchEpisodeNfo(Script1.groovy:9)
        at Script1$_run_closure1.doCall(Script1.groovy:89)
        at Script1.run(Script1.groovy:80)
        at net.filebot.cli.ScriptShell.evaluate(Unknown Source)
        at net.filebot.cli.ScriptShell.runScript(Unknown Source)
        at net.filebot.cli.ArgumentProcessor.runScript(Unknown Source)
        at net.filebot.cli.ArgumentProcessor.run(Unknown Source)
        at net.filebot.Main.main(Unknown Source)

Error (o_O)
```
